name: Linux Meson Qemu Aarch64

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup Meson
        run: pip install meson
      - name: Setup aarch64-linux-gnu-gcc
        run: |
          sudo apt-get install gcc-aarch64-linux-gnu
          sudo apt-get install g++-aarch64-linux-gnu
      - name: Setup Qemu
        run: |
          git clone --depth=1 --branch v7.2.2 https://gitlab.com/qemu-project/qemu.git
          mkdir build-qemu
          cd build-qemu
          ../qemu/configure --target-list=aarch64-linux-user
          make -j64
          sudo make install

      - name: Tests
        run: |
          meson setup --cross-file aarch64-linux-gnu-gcc.txt build-aarch64-linux-eabi
          meson compile -C build-aarch64-linux-eabi
          meson test -C build-aarch64-linux-eabi
